server:
  port: 10086
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
spring:
  application:
    name: eureka-server